In [1]:
#Folders with Images
Folders = ["1_Pineapples", "2_Strawberry", "3_Banana", "4_Lychee", "5_Apple",
           "6_Raspberry", "7_Peach", "8_Orange", "9_Lime", "10_Pomegranate"]

In [2]:
#Convert Pineapple Images to Arrays
#Reference for Converting JPGs to Arrays
#https://scikit-image.org/docs/dev/user_guide/getting_started.html

#Conversion 3d array to 2d
# nsamples, nx, ny = ModelJPGArrays.shape
# d2_train_dataset = ModelJPGArrays.reshape((nsamples,nx*ny))

import os
from skimage import io, color

#Define a list of all JPG Arrays
ModelJPGArrays = []
Labels = []

#Append ModelJPGArrays 
directory = 'Fruits/1_Pineapples/'
PineappleArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/1_Pineapples/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        PineappleArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(1)
        
directory = 'Fruits/2_Strawberry/'
StrawberryArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/2_Strawberry/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        StrawberryArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(2)   
        
directory = 'Fruits/3_Banana/'
BananaArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/3_Banana/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        BananaArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(3)
        
directory = 'Fruits/4_Lychee/'
LycheeArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/4_Lychee/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        LycheeArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(4)  
        
directory = 'Fruits/5_Apple/'
AppleArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/5_Apple/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        AppleArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(5)  
        
directory = 'Fruits/6_Raspberry/'
RaspberryArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/6_Raspberry/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        RaspberryArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(6)
        
directory = 'Fruits/7_Peach/'
PeachArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/7_Peach/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        PeachArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(7)
        
directory = 'Fruits/8_Orange/'
OrangeArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/8_Orange/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        OrangeArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(8)

directory = 'Fruits/9_Lime/'
LimeArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/9_Lime/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        LimeArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(9)

directory = 'Fruits/10_Pomegranate/'
PomegranateArrays = []
for file in os.listdir(directory):
   if file.endswith(".jpg"):
        jpg = (f'Fruits/10_Pomegranate/{file}')
        jpgarray = io.imread(jpg)
        jpgarray = jpgarray.reshape(-1)
#         nsamples, nx, ny = jpgarray.shape
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)
#         jpgarray = color.rgb2gray(jpgarray)
        PomegranateArrays.append(jpgarray)
        ModelJPGArrays.append(jpgarray)
        Labels.append(10)

In [3]:
#Confirm Length of All Fruit Arrays
#Length of Labels should be 10 x 24
print(len(PineappleArrays), len(StrawberryArrays), len(BananaArrays), len(LycheeArrays), len(AppleArrays), len(RaspberryArrays), len(PeachArrays), len(OrangeArrays), len(LimeArrays), len(PomegranateArrays))
print(len(Labels))
print(len(ModelJPGArrays))

24 24 24 24 24 24 24 24 24 24
240
240


In [5]:
#Proof That they are all 2d arrays

for i in ModelJPGArrays:
    print(i.shape)

[255 255 255 ... 255 255 255]
[255 254 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[255 255 253 ... 255 255 255]
[255 254 255 ... 255 255 255]
[255 255 253 ... 255 255 255]
[255 255 253 ... 255 255 255]
[255 254 253 ... 255 255 255]
[254 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[254 255 255 ... 255 255 255]
[255 254 253 ... 255 255 255]
[255 255 255 ... 255 255 255]
[247 255 251 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 253 ... 255 255 255]
[255 254 253 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 255 ... 255 255 255]
[255 255 2

In [6]:
#https://github.com/mGalarnyk/Python_Tutorials/blob/master/Sklearn/Logistic_Regression/LogisticRegression_toy_digits.ipynb
#Import Machine Learning dependencies
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import numpy as np 

import matplotlib.pyplot as plt
import seaborn as sns

# Used for Confusion Matrix
from sklearn import metrics

In [22]:
# nsamples, nx, ny = ModelJPGArrays[1].shape
# d2_ModelJPGArrays = ModelJPGArrays[1].reshape((nsamples,nx*ny))

In [7]:
# test_size: what proportion of original data is used for test set
x_train, x_test, y_train, y_test = train_test_split(
    ModelJPGArrays, Labels, test_size=0.25, random_state=0)

In [8]:
#Make Instance of Logistic Regression Model
FruitRegr = LogisticRegression()

In [9]:
len(x_train)

180

In [10]:
#Train Model
FruitRegr.fit(x_train, y_train)

//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
//anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
Predictjpg = ('Fruits/To_Predict/2.jpg')
Predictjpgarray = io.imread(Predictjpg)
# Predictjpgarray = Predictjpgarray.reshape(-1)
Predictjpgarray.shape
# FruitRegr.predict(Predictjpgarray.reshape(-1,1))
#         jpgarray = jpgarray.reshape((nsamples,nx*ny))
#         jpgarray = jpgarray.transpose(2,0,1).reshape(3,-1)

(100, 100, 3)

In [41]:
x=Predictjpgarray.reshape(1,-1)
x.shape

(1, 30000)

In [43]:
FruitRegr.predict(x)

array([3])

array([6])

array([6])

array([6])